[2025-07-18T09:06:54.427+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-18T09:06:54.432+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-07-18T02:02:29.219580+00:00 [queued]>
[2025-07-18T09:06:54.434+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-07-18T02:02:29.219580+00:00 [queued]>
[2025-07-18T09:06:54.435+0700] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-07-18T09:06:54.455+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2025-07-18 02:02:29.219580+00:00
[2025-07-18T09:06:54.458+0700] {standard_task_runner.py:63} INFO - Started process 4015 to run task
[2025-07-18T09:06:54.460+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2025-07-18T02:02:29.219580+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpoee4_w2v']
[2025-07-18T09:06:54.460+0700] {standard_task_runner.py:91} INFO - Job 57: Subtask transform_load_weather_data
[2025-07-18T09:06:54.501+0700] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2025-07-18T02:02:29.219580+00:00 [running]> on host MSI.
[2025-07-18T09:06:54.553+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='menglimchea@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T02:02:29.219580+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-18T02:02:29.219580+00:00'
[2025-07-18T09:06:54.554+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-18T09:06:54.557+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-18T09:06:54.557+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow/dags/weather_dag.py", line 27, in transform_load_data
    time_of_record = datetime.fromtimestamp(data['dt'] + data['timezone'], tz=timezone.utc)
                                                                              ^^^^^^^^
NameError: name 'timezone' is not defined
[2025-07-18T09:06:54.561+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2025-07-18T02:02:29.219580+00:00, execution_date=20250718T020229, start_date=20250718T020654, end_date=20250718T020654
[2025-07-18T09:06:54.578+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task transform_load_weather_data (name 'timezone' is not defined; 4015)
[2025-07-18T09:06:54.593+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-18T09:06:54.599+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T09:06:54.599+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
