[2025-07-17T14:10:14.536+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-17T14:10:14.542+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-07-17T07:10:10.055776+00:00 [queued]>
[2025-07-17T14:10:14.545+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-07-17T07:10:10.055776+00:00 [queued]>
[2025-07-17T14:10:14.545+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-17T14:10:14.560+0700] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-07-17 07:10:10.055776+00:00
[2025-07-17T14:10:14.564+0700] {standard_task_runner.py:63} INFO - Started process 4484 to run task
[2025-07-17T14:10:14.566+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-07-17T07:10:10.055776+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp2zmiaabp']
[2025-07-17T14:10:14.566+0700] {standard_task_runner.py:91} INFO - Job 3: Subtask is_weather_api_ready
[2025-07-17T14:10:14.608+0700] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-07-17T07:10:10.055776+00:00 [running]> on host MSI.
[2025-07-17T14:10:14.658+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='menglimchea@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T07:10:10.055776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T07:10:10.055776+00:00'
[2025-07-17T14:10:14.659+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-17T14:10:14.659+0700] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-07-17T14:10:14.660+0700] {http.py:137} INFO - Poking: /data/2.5/weather?q=Phnom Penh&APPID=w8KHqpk7yPfNmW9d
[2025-07-17T14:10:14.663+0700] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2025-07-17T14:10:14.996+0700] {http.py:199} ERROR - HTTP error: Unauthorized
[2025-07-17T14:10:14.996+0700] {http.py:200} ERROR - {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
[2025-07-17T14:10:14.996+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-17T14:10:14.998+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 197, in check_response
    response.raise_for_status()
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=Phnom%20Penh&APPID=w8KHqpk7yPfNmW9d

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 158, in poke
    raise exc
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
               ^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 187, in run
    return self.run_and_check(session, prepped_request, extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 238, in run_and_check
    self.check_response(response)
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 201, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 401:Unauthorized
[2025-07-17T14:10:15.006+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=manual__2025-07-17T07:10:10.055776+00:00, execution_date=20250717T071010, start_date=20250717T071014, end_date=20250717T071015
[2025-07-17T14:10:15.019+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task is_weather_api_ready (401:Unauthorized; 4484)
[2025-07-17T14:10:15.060+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-17T14:10:15.066+0700] {logging_mixin.py:188} WARNING - /home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
[2025-07-17T14:10:15.071+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-17T14:10:15.071+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
